config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  get 'todos', to: 'todos#index'
  get 'todos/new', to: 'todos#new'
  get 'todos/list', to: 'todos#list'
  get 'todos/:id', to: 'todos#show', as: 'todo'
  get 'todos/:id/edit', to: 'todos#edit'
  get 'todos/:id/complete', to: 'todos#complete', as: 'complete'

  post 'todos', to: 'todos#create'

  patch 'todos/:id', to: 'todos#update'

  delete 'todos/:id', to: 'todos#destroy'

  root "todos#index"

#  root 'todos#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/todo.rb
class Todo < ApplicationRecord
  validates :description, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/todos_controller.rb
class TodosController < ApplicationController
  before_action :find_todo, only: [:show, :edit, :update, :destroy, :complete]

  def index
    @todos = Todo.all
  end

  def new
    @todo = Todo.new
  end

  def create
    @todo = Todo.new(todo_params)
    if @todo.save
      redirect_to root_path
    else
      redirect_to root_path, notice:'No guardado'
    end
  end

  def show
  end

  def edit
  end

  def update
    @todo.update(todo_params)
    redirect_to root_path
  end

  def destroy
    @todo.destroy
    redirect_to root_path
  end

  def complete
    @todo.completed = true
    @todo.save
    redirect_to root_path
  end

  def list
    @todos = Todo.all
    @todos_completados = Todo.where(completed: true)
    @todos_no_completados = Todo.where(completed: [false, nil])
  end

  private
  def todo_params
    params.require(:todo).permit(:description)
  end

  def find_todo
  @todo = Todo.find(params[:id])
  end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/todos_helper.rb
module TodosHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default ">
  <div class="container">
    <ul class="nav navbar-nav">
      <li><%= link_to 'Home', root_path %></li>
      <li><%= link_to 'Crear', todos_new_path %></li>
      <li><%= link_to 'Lista', todos_list_path %></li>
  </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TodoApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/navbar' %>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

  </body>
</html>

app/views/todos/_form.html.erb
<div class="container">

<%= form_with model: @todo, local: true do |f| %>
  <%= f.label "Crear ToDo" %> <br>
  <%= f.text_field :description %> <br> <br>
  <%= f.submit "Enviar" %> <br> <br>
  <%= link_to "Volver", root_path %> <br>
<%end%>

</div>

app/views/todos/edit.html.erb
<%= render 'todos/form' %>

app/views/todos/index.html.erb
<% @todos.each do |todo| %>

  <div class="well container">
    <%= link_to todo.description, todo %>

  <% if todo.completed == true %>
    <strong>Listo</strong>
  <% else %>
    <button type="button" class="btn btn-lg btn-success">
      <%= link_to "Completar", complete_path(todo) %></button>
  <% end %>
  <button type="button" class="btn btn-sm btn-danger"><%= link_to "Borrar", todo, method: :delete %></button>

  </div>
<% end %>

<div class="container">
  <button type="button" class="btn btn-lg btn-info"><%= link_to "Nuevo ToDo", todos_new_path %></button>
</div>

app/views/todos/list.html.erb
<div class="container row text-center">

  <div class="col-md-6">
    <h1>No Completados</h1>
  <% @todos_no_completados.each do |t| %>
    <p><%= t.description %></p><br>
  <% end %>
  </div>

  <div class="col-md-6">
    <h1>Completados</h1>
  <% @todos_completados.each do |t| %>
    <p><%= t.description %></p><br>
  <% end %>
  </div>

</div>

app/views/todos/new.html.erb
<%= render 'todos/form' %>

app/views/todos/show.html.erb
<h1><%= @todo.description %></h1>